# Generated by Django 6.0.2 on 2026-04-04 10:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('grade_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_no', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('ext_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.TextField(default='N/A')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(default='N/A', max_length=20)),
                ('licno', models.CharField(default='N/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('ext_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('student_guardian', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('ext_name', models.CharField(max_length=20)),
                ('relationToStudent', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=20)),
                ('semester', models.CharField(blank=True, max_length=20, null=True)),
                ('school_year', models.CharField(blank=True, max_length=10, null=True)),
                ('room', models.CharField(default='N/A', max_length=20)),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.gradelevel')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enrollee', 'Enrollee'), ('enrolled', 'Enrolled'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='enrollee', max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollment.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollment.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollment.course')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=10)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('room', models.CharField(max_length=20)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollment.instructor')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollment.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='enrollment.subject')),
            ],
        ),
    ]
