# Generated by Django 6.0.2 on 2026-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='licno',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
    ]
