# Generated by Django 6.0.2 on 2026-04-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_alter_instructor_licno'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='prev_grade',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
