# Generated by Django 6.0.2 on 2026-04-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_enrollment_prev_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='school_year',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'grade', 'prev_grade'), name='unique_student_grade'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('first_name', 'middle_name', 'ext_name', 'last_name', 'date_of_birth'), name='unique_student_identity'),
        ),
    ]
