# Generated by Django 6.0.2 on 2026-04-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_remove_section_school_year_enrollment_school_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(blank=True, default=0, max_length=20),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], max_length=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('session', models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon')], max_length=2)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.student')),
            ],
            options={
                'unique_together': {('student', 'section', 'date')},
            },
        ),
    ]
