# Generated by Django 6.0.2 on 2026-04-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_alter_student_contact_number_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='session',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='status',
        ),
        migrations.AddField(
            model_name='attendance',
            name='am_status',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='pm_status',
            field=models.CharField(blank=True, choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lrn_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
